name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
      - run: yarn test
  release-package:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: yarn release

    
