name: test

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URI: ${{vars.DATABASE_URI}}
      PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}
      ALGOLIA_APPLICATION_ID: ${{secrets.ALGOLIA_APPLICATION_ID}}
      ALGOLIA_ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
      ALGOLIA_INDEX: ${{secrets.ALGOLIA_INDEX}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
